- name: Windows Update All Patches
  hosts: all
  tasks:
   # Check if there are missing updates
    - block:
        - name: Check for missing updates.
          win_updates: state=searched
          register: update_count
      tags: check
    #Install missing updates only if at least one is missing
    
    - block:
        - name: Install missing updates.
          win_updates:
            category_names:
              - Application
              - Connectors
              - CriticalUpdates
              - DefinitionUpdates
              - DeveloperKits
              - FeaturePacks
              - Guidance
              - SecurityUpdates
              - ServicePacks
              - Tools
              - UpdateRollups
              - Updates
          register: update_result
        - name: Reboot, if needed.
          win_reboot:
          when: update_result.reboot_required
      when: update_count.found_update_count|int >= 1
